FROM node:latest

RUN mkdir -p app/Back-End/Products

COPY Products app/Back-End/Products

WORKDIR app/Back-End/Products

RUN npm install express.js
RUN npm install dotenv
RUN npm install mongoose

EXPOSE 2035

CMD [ "node" "products.js" ]
